- go.mod
Only necessary change is in go.mod, Circle is already on 1.13.
> Go: use Go 1.13

- state.go
Deposed resources were missing from the `StateValues` output. This was fixed in https://github.com/hashicorp/terraform/pull/23027 (merged, but likely won't be released for at least two weeks).
> state: add new DeposedKey to state resources

- go.mod
- go.sum
This is mostly to pin cty to a stable version, rather than a revision, although given the exposure of cty here (just `cty.Type`) I doubt it has any real effect.
> Bump go-cty to latest (1.2.1)

- config.go
At this point in time it is not easy to add a test case as it is completely reliant on Terraform 0.13 being available. Some work needs to be done to support multiple terraform versions within the test scenarios.
> Add depends_on support to module calls

- .circleci/config.yml
- testdata/Makefile
Instead of using dockerhub (which will enforce rate limiting on anonymous image pulls starting Nov 1st), we're moving projects to our mirror at `docker.mirror.hashicorp.services`. We're updating CircleCI configs, docker compose, dockerfiles, relevant parts of Makefiles, and travis configs. Github actions are excluded, as Github is handling the issue on their end. LMK if you have any q's, otherwise feel free to approve and merge on your own!
> Use docker mirror

- schemas.go
This has always been `plain`: https://github.com/hashicorp/terraform/blob/c258e8efbb3146a79f3e47ce934722580407036d/command/jsonprovider/attribute.go#L23, it was just unfortunately missed in the initial PR.
I have a workaround in place where I use this library:
https://github.com/hashicorp/terraform-schema/blob/0c9744a02c6568f0d157e48c24f281babe865de9/schema/schema_merge.go#L259-L262
and this patch would allow me to remove it.
> Fix SchemaDescriptionKindPlain value (plaintext -> plain)

- version.go
- version_test.go
This is likely to conflict with https://github.com/hashicorp/terraform-json/pull/23 - I can rebase the other one when either of these PRs are merged.
--- 
It is planned to parse the JSON output in `terraform-exec` at some point as per https://github.com/hashicorp/terraform-exec/issues/13 and this PR would therefore support these efforts.
The struct is practically copy&paste of the one used in core:
https://github.com/hashicorp/terraform/blob/ae025248cc0712bf53c675dc2fe77af4276dd5cc/command/version.go#L26-L32
I just added `omitempty` to `platform` since that was introduced in v0.15, although I don't expect anyone will actually use these structs for marshalling.
> Add version output

- state.go
State values can contain numbers that are larger than `float64` can
precisely represent. `json.Unmarshal` when unmarshaled into an
`interface{}` uses `float64` to represent numbers by default. To
properly retain precision for numbers, we need to use a custom
`json.Decoder` with the `UseNumber()` method called on it, which will
use `json.Number` (a `string` alias) to store the numbers, preserving
their precision.
> Use json.Number instead of float64 when parsing state.

- state.go
Some consumers still rely on JSON numbers being float64s. To avoid
breaking them, we make the new json.Number behavior opt-in using a flag
on the State struct.
> Make json.Number behavior optional.

- schemas.go
This reflects a change introduced a while ago in https://github.com/hashicorp/terraform/pull/20949 and also changes introduced as part of https://github.com/hashicorp/terraform/pull/28055, https://github.com/hashicorp/terraform/pull/27699 and https://github.com/hashicorp/terraform/pull/27793
The mentioned PRs do _not_ change anything about the underlying _syntax_ that couldn't be already expressed using the `SchemaAttribute.AttributeType`, however these changes allow the SDK and providers to communicate some additional metadata that cannot be communicated via "pure" `cty.Type`, such as sensitivity, or description for each individual attribute.
These new features are not in use by the SDK nor the built-in `terraform` provider yet (AFAIK), but this allows us to support it when the time …
> Reflect v0.15 schema changes

- schemas.go
The previous implementation was not wrong, but this patch just makes it easier to use `NestingMode` in a switch statement where `string` and custom type otherwise cannot be mixed.
> Use custom type for NestingMode type

- config.go
- plan.go
- plan_test.go
- testdata/basic/plan-0.15.json
Fixes #31 
Reflects changes made in https://github.com/hashicorp/terraform/pull/28201
> Reflect 0.15 sensitivity fields in plan & config

- go.mod
- go.sum
- sanitize/copy.go
- sanitize/copy_test.go
- sanitize/sanitize_change.go
- sanitize/sanitize_change_test.go
- sanitize/sanitize_plan.go
- sanitize/sanitize_plan_test.go
- sanitize/sanitize_plan_variables.go
- sanitize/sanitize_plan_variables_test.go
- sanitize/sanitize_state.go
- sanitize/sanitize_state_test.go
- sanitize/testdata/basic.golden
- sanitize/testdata/basic.json
This adds a new package and functions for sanitization of values marked
as sensitive in the plan, where we can get particular data to do it.
This data is derived in a number of ways, also documented in the
top-level SanitizePlan function:
* ResourceChanges are sanitized based on BeforeSensitive and
AfterSensitive fields.
* Variables are sanitized based on variable config data found in the
root module of the Config.
* PlannedValues are sanitized based on the values found in
AfterSensitive in ResourceChanges. Outputs are sanitized according to
the appropriate sensitivity flags provided for the output.
* PriorState is sanitized based on the values found in BeforeSensitive
in ResourceChanges. Outputs are sanitized according to the appropriate
sensitivity flags provided for the output.
* …
> sanitize: allow for the sanitization of sensitive values

- CODEOWNERS
The `CODEOWNERS` syntax assumes that co-owners are listed on the same line.
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#example-of-a-codeowners-file
The format is `path owner` and with the same path it seems to be interpreted as "last owner wins", which isn't what was intended.
> Update CODEOWNERS to fix syntax

- plan.go
This PR adds the `ResourceDrift` field to terraform-json. This field has been included in plan JSON representations since v0.15.2. Furthermore, this library will be utilized by tfc-agent in order to redact Terraform plans. Changes resulting from resource drift consist of one of those redaction paths.
> Add resource drift field to plan

- plan.go
Add the import fields to the plan introduced in Terraform v1.5. See https://github.com/hashicorp/terraform/blob/main/internal/command/jsonplan/plan.go.
> plan: add plannable import fields for v1.5

- README.md
By design, the `terraform-json` library is not always suitable for every application. Its name and prominence may cause those integrating with Terraform to assume otherwise.
This commit expands the README to attempt to clarify situations where the `terraform-json` library is not appropriate, explaining why and what to do instead.
> Update README to explain when not to use this library

- plan.go
This is a missing field that indicates which attributes (by index) are responsible for the overall replacement of a resource.
> Add `ReplacePaths` to `Change` struct

- plan.go
Ref: https://github.com/hashicorp/terraform/pull/35065
This PR adds the JSON data for deferred actions in the planfile. This data is only available when utilizing the deferred action experiment introduced in Terraform [`v1.9.0-alpha20240404`](https://github.com/hashicorp/terraform/releases/tag/v1.9.0-alpha20240404). The actual JSON output changes referenced above will be released in the upcoming alpha release.
> tfjson: Add `DeferredChanges` and `Complete` to `Plan` JSON

- plan.go
Ref: https://github.com/hashicorp/terraform/pull/34642
Since [`Complete` was first present in `Terraform 1.8`](https://github.com/hashicorp/terraform/blob/v1.8.0/internal/command/jsonplan/plan.go#L67), we should make it a pointer to allow downstream tooling to determine if it was explicitly set
> tfjson: Update `Complete` to a pointer value for older Terraform versions

- schemas.go
- schemas_test.go
- testdata/write_only_attribute_on_resource/schemas.json
Closes TF-22967
This PR:
* adds support for the new write-only schema behaviour.
* The new write-only data was added to the `terraform providers schema -json` command in https://github.com/hashicorp/terraform/pull/35989
* refactors some pre-existing tests when adding new tests
I've not included any changes in the `sanitize` package because that package appears to be specific to Sensitive values, and is irrelevant to ephemeral resources & write-only attributes.
> Add support for write-only attributes

- logging_query.go
- logging_test.go
https://github.com/hashicorp/terraform/pull/37612
This adds an the `identity_version`  field to the struct that represents the `list_resource_found` message. This hinges on a new terraform release that contains the changes in the above-mentioned related PR-
In plain English, describe your approach to addressing the issue linked above. For example, if you made a particular design decision, let us know why you chose this path instead of another solution.
Are there any changes to security controls (access controls, encryption, logging) in this pull request? If so, explain.
> tf query: add identity version for the list_resource_found message

- config.go
- expression.go
- metadata.go
- parse_test.go
- plan.go
- plan_test.go
- schemas.go
- state.go
- state_test.go
- testdata/invalid/plan.json
- testdata/invalid/state.json
- validate.go
Fixes https://hashicorp.atlassian.net/browse/SECVULN-24144
Use JSON validation from [Go's JSON parser](https://pkg.go.dev/encoding/json#pkg-overview) to reject malformed JSON inputs in `State` and `Plan` structs.
Are there any changes to security controls (access controls, encryption, logging) in this pull request? No.
> Add documentation to `UnmarshalJSON` implementations
